### ISSUE TITLE
-FILTER error. output not going to stdout

### ISSUE THREAD

**Issue by billou2k** [cloudera/impala-tpcds-kit#19]
I Just cloned impala-tpcds-kit. When running ./gen-dims.sh and ./gen-facts.sh
I get: 
ERROR: option 'FILTER' or its argument unknown.
the usage text that follows shows "_FILTER" should be used instead. 
There is no more error, but the data is copied to a local file instead of stdout so no data is piped to hdfs 
as the script intends to:

  ${TPCDS_ROOT}/tools/dsdgen \
    -TABLE $t \
    -SCALE ${TPCDS_SCALE_FACTOR} \
    -DISTRIBUTIONS ${TPCDS_ROOT}/tools/tpcds.idx \
    -TERMINATE N \
    -FILTER Y \
    -QUIET Y | hdfs dfs -put - ${FLATFILE_HDFS_ROOT}/${t}/${t}.dat &

**Comment by gregrahn** [comment]
I recently made some changes to the repo.  This should get you back the the version that works.
```
git clone https://github.com/gregrahn/tpcds-kit.git
cd tpcds-kit
git reset --hard eff5de2c30337b71cc0dc1976147742d2c65d378
```

**Comment by billou2k** [comment]
Thanks, that fixed it!
