### ISSUE TITLE
lack of table

### ISSUE THREAD

**Issue by Minkyolyy** [cloudera/impala-tpcds-kit#24]
why just 10 tables  maybe queries sql need 25tables

**Comment by linwukang** [comment]
same issue, and how to create the 15 lacked table?

**Comment by dagirl143** [comment]
add them to the generate script for the dimension tables.

here's an example of mine where i put all the dimension tables in one run:
`for t in date_dim time_dim customer customer_address customer_demographics household_demographics item promotion store call_center catalog_page income_band reason ship_mode warehouse web_page web_site`

Script in reference: gen-dims.sh

**Comment by anildu** [comment]
How to generate a data for those missing tables?

**Comment by gregrahn** [comment]
Fixed with 611fa0a425e76acaeb205e57c7279ecc4e517919
