### ISSUE TITLE
Exception when generating store_sales table.

### ISSUE THREAD

**Issue by bmv126** [cloudera/impala-tpcds-kit#29]
Below exception is seen while generating data for store_sales table.

org.apache.hadoop.ipc.RemoteException(org.apache.hadoop.hdfs.server.namenode.LeaseExpiredException): No lease on /user/bmv/tpcds/st ore_sales/store_sales_3_30.dat._COPYING (inode 16720): File does not exist._

**Comment by alexmc6** [comment]
I got something similar because I hit my HDFS disk quota
