### ISSUE TITLE
load-store-sales index out of range

### ISSUE THREAD

**Issue by liupeirong** [cloudera/impala-tpcds-kit#30]
load-store-sales.py tries to [read ](https://github.com/cloudera/impala-tpcds-kit/blob/master/load-store-sales.py#L24)'--mem_limit' from http://{impalad}:25000/vars?raw, but it's not there, causing error "list index out of range".

**Comment by roycem90** [comment]
i m having the same trouble, any help??

**Comment by alexmc6** [comment]
I have seen someone hard code this value

  # Returning a static value since /varz?raw doesn't return the expected content on new Impala versions
  return 6139445248/(1024**3)

**Comment by roycem90** [comment]
ya we got it running with stack hard coded value too

**Comment by gregrahn** [comment]
Fixed with 611fa0a425e76acaeb205e57c7279ecc4e517919
