### ISSUE TITLE
impala-insert failing

### ISSUE THREAD

**Issue by cab2222** [cloudera/impala-tpcds-kit#33]

**Comment by cab2222** [comment]
impala-insert.sql fails with a memory limit exceeded which I am trying to increase but also the hint clustered is not used with my version (impalad version 2.5.0-cdh5.7.0) . any ideas of an alternative I could use to clustered?

**Comment by gregrahn** [comment]
With such an old version (almost 3 years old) you will have to load the fact tables by limiting the number of partitions being loaded at one time in a multi-pass format.

**Comment by cab2222** [comment]
Thank you

Will look at it tomorrow.

On 16 Jan 2019 20:18, Greg Rahn <notifications@github.com> wrote:

With such an old version (almost 3 years old) you will have to load the fact tables by limiting the number of partitions being loaded at one time in a multi-pass format.

**Comment by cab2222** [comment]
I can't get impala updated on our work system which is annoying. So in impala-insert.sql I am currently trying to split the table for example, catalog_sales, by splitting the partitioning further. Is that the right way to go about it, and could you recommend the best way to do that split. Many thanks for your cooperation.

**Comment by gregrahn** [comment]
The problem is that it takes a significant amount of memory to insert into every partition from every host, so the hints deal with that.  On older versions you will have to limit the number of partitions being inserted into by adding a predicate on the text table. For example, taking 20 values of `ss_sold_date_sk` from `store_sales` at a time.

**Comment by cab2222** [comment]
Thanks Greg. I have found another database that I might use if I can't get this working. Thanks for the help.
