### ISSUE TITLE
query39.sql contains 2 queries

### ISSUE THREAD

**Issue by Peter-Ebert** [cloudera/impala-tpcds-kit#35]
As stated, 39 has the query twice.

**Comment by gregrahn** [comment]
TPC-DS has 4 query templates that contain 2 queries each:

- query14
- query23
- query24
- query39

The 2nd query in 39 contains an extra predicate `and inv1.cov > 1.5` so they are not identical.
https://github.com/cloudera/impala-tpcds-kit/blob/master/query-templates/query39.tpl#L90
